### ISSUE TITLE
It does not find .mp3 files in the share.

### ISSUE THREAD

**Issue by mcv93us** [nov30th/ha-hoho-google-media-center#1]
Greetings,
I am trying this media center because I want to play some MP3s that I have on my NAS.
I mapped the NAS path to HA via SMB with path "media_dirs:"
musica: '/config/media/SMB/NAS/Musica'
The folder is physically present on the HA being the mount point while the subfolders are all on the NAS.
If I open the browser with Chromecast I can play the music without problems and from the developer tools menu the mapped and working content_id is "/media/musica/".
From NodeRED, however, it does not find any folders and obviously no files, in practice it is as if it did not see the folders mounted on the NAS.
In the Playlist mapping node I put the path on "one_media_dirs_in_ha_conf" = "musica: /config/media/SMB/NAS/Musica"
which matches that of media_dirs but it doesn't work, I don't understand where the error is.

In addition to this in the "File Listener" node in the "Start Folder" and "File Pattern" items there is written "Vincent Qiu" and "by HOHO``" ... is this correct ???
Thank you for the huge work you are doing here !!!

**Comment by mcv93us** [comment]
Thanks for the reply.
Yes, I created the "reload playlist" button and it loads my playlists instantly.
I found out what the problem was, as Node-RED is in another container it doesn't get to see the SMB share under HA, I had to create the share in my OS. host under Raspbian, now works perfectly.
I would like to ask you if it is possible to implement a couple of features which I think can be very useful:

The first is to exclude certain folders, in my case
 on the NAS share I also have a "#recycle" folder which I don't want to see appear as a playlist.

The second feature I think is more complex to create but it would be useful to distinguish the musical genre as well.
In my MP3 folder I have created folders by musical genre: classical, light, anime, etc ...
In each of those folders there are other subfolders with the authors (or the series) and inside other folders with the various albums.
In practice, the "first level" should feed the list of the musical genre and the second level should feed the list of playlists.
Do you think something like this is achievable?
Node-RED I only installed it a couple of days ago and I have yet to understand how it works before attempting to make any changes to the project.

**Comment by mcv93us** [comment]
Sorry if I still bother you but I noticed a problem that you have surely faced and solved.
I turned off the Raspberry to clean the cooling fan and when I turned on Home Assistant it started in safe mode with an error on mounting SMB shares, as if the mounting of folders takes place after starting Home Assistant which therefore goes to safe mode .
I did the editing via fstab, like this:
``
//192.168.1.3/music /usr/share/hassio/homeassistant/media/SMB/NAS/Musica cifs username=xxxxx,password=xxxx,workgroup=WORKGROUP,users,auto,user_xattr,_netdev,x-systemd.automount 0 0
``
while I was reading on the forum that you solved it with rc.local, at the beginning I had tried with rc.local putting this:
``
mount -t cifs -o username=xxxxx,password=xxxxx,domain=WORKGROUP //192.168.1.3/music "/usr/share/hassio/homeassistant/media/SMB/NAS/Musica"
``
and it worked until I realized that Rasbian OS gave writing errors because it turned out that I had the SSD 100% full, after unmounting the volume everything was back as before.
Now I use fstab again to mount the volume but every time I reboot the HA system it goes into safe mode until I reload it from Docker.
If you can advise me what to do I will be eternally grateful !!!

**Comment by mcv93us** [comment]
Safe mode appears to me only if I mount the shares from fstab, instead if I do it from rc.local then it works for me.
At first I had a problem using rc.local as during the scheduled nightly backup it created a giant temporary file because it also backed up shared folders.
The partial backup did not allow me to exclude the path of the subfolders of "config /" so I moved the share under "media /" and now everything works perfectly.
Thanks again for the help.

Now I will try to see if it is possible to implement the exclusion of certain folders from the playlist and to manage the music genres.

**Comment by nov30th** [comment]
sounds good, just let me know if you have other issues with these node-red codes.
For the folders, you could just add a node that filters the array items in node-red.
I just close this issue as it is functional. Feel free to open an issue if you have any questions. Currently, I would still assume this code is for basic music playing, won't be an adv player.
