### ISSUE TITLE
Doesn´t play more than a music title

### ISSUE THREAD

**Issue by nickelb** [nov30th/ha-hoho-google-media-center#3]
Thanks for the great work.
But it plays only one random music title and stops after the song.
If it starts the next time it runs with another song.
How can it play more than one random title?

**Comment by nov30th** [comment]
You might need to give more details in node-red debug output with debug output node attached I am not sure wut the problem is at your side.
It is designed to play songs continuously.

**Comment by nov30th** [comment]
You might also wanna check the node which "checks media player status and restart the play node", the media player status might have not been submitted to the node-red. Check the media player entity id.
